### ISSUE TITLE
Version in doxy documentation

### ISSUE THREAD

**Issue by heinovski** [michele-segata/plexe-veins#10]
The [script](https://github.com/michele-segata/plexe-veins/blob/master/doc/version.sh) to generate the version number for the doxy documentation (merged in 81ac2ceb18e832903a7c28e6a2f25511cd9e4789)  does not work with Plexe.

The script parses git tags beginning with `plexe-` but this repository does not contain any (e.g., for marking released versions such as `plexe-3.0a1`). To solve this issue, versions should be labelled with git tags instead of branches. Alternatively, the script should be changed to operate on branches.

Additionally, 0811fcdbc6353a1c99c6b9898a071983609e42bf introduced another script to print the version number, which works and could also be used for the generation of the documentation. One script to extract the version number should be sufficient ;-)

**Comment by michele-segata** [comment]
I've been pushing tags to github. Now the script properly works.

With respect to the duplicated script for extracting the version, I would ask @sommer as he introduced it. Is the second script (`print-plexe-version`) required? I see that in `veins` only `doc/version.sh` exists.

**Comment by sommer** [comment]
> Is the second script (`print-plexe-version`) required? I see that in `veins` only `doc/version.sh` exists.

As of Veins 5.0-alpha2, a similar script <https://github.com/sommer/veins/blob/veins-5a2/print-veins-version> exists.

In my opinion, the two scripts serve different purposes:
- one (`/print-bla-bla`) looks at the source code and can be used by build systems and compilers to check if a compatible version of Plexe is being used as a basis for a custom simulation. I'm guessing these checks need not be more coarse-grained than release versions.
- one (`/doc/bla-bla`) looks at the current git checkout to give a user a clue which version their documentation was last compiled for. I'm guessing it makes sense to have this script finer-grained (per-commit) information in the compiled documentation, but could just as well live with simply delegating to the `/print-bla-bla` script here (which didn't exist in earlier versions)

**Comment by michele-segata** [comment]
@jheinovski Are you satisfied with @sommer 's answer? If so I think we can close this issue.

**Comment by heinovski** [comment]
I just wanted to point out the existence of these two scripts, but, as @sommer described, both serve a different purpose. Therefore, I am fine with having both and closing this issue as well as delegating the printing to the other script for compilers - Your choice ;-)
