### ISSUE TITLE
instant plexe run error

### ISSUE THREAD

**Issue by ynuwm** [michele-segata/plexe-veins#11]
Hi, michele-segate, thanks for your code. I install the instant plexe on my VmWare virtual machine, when I run the examples, it can run successfully by sumo. But I want to run it in sumo-gui, it stucks in the map loading interface.  Before run examples, I just run:

`python "/home/plexe/src/plexe-veins/sumo-launchd.py" -vv -c "/home/plexe/src/plexe-sumo/bin/sumo-gui"`

Can you help me find what's wrong? Thank you.

**Comment by ynuwm** [comment]
I reinstall the instant-plexe, I run this in terminal:
`python sumo-launchd.py /home/plexe/src/plexe-sumo/bin/sumo-gui`
but it encouter this:
`Superfluous command line arguments: "/home/plexe/src/plexe-sumo/bin/sumo-gui"`

**Comment by ynuwm** [comment]
when I close the sumo-gui windows, the console in omnet appear this：

>>>>>>>>>>>>>>>>>>>>>>>>>
Plugin path: ./plugins
Loading configuration... done.

RUNTIME ERROR. A cRuntimeError exception is about to be thrown, and you
requested (by setting debug-on-errors=true in the ini file) that errors
abort execution and break into the debugger.

You should now probably be running the simulation under gdb or another
debugger. The simulation kernel will now raise a SIGINT signal which will
get you into the debugger. If you are not running under a debugger, you can
still use the core dump for post-mortem debugging. Once in the debugger,
view the call stack (in gdb: "bt" command) to see the context of the
runtime error.

<!> Error launching TraCI server ("sumo-gui --remote-port 50501 --seed 0 --configuration-file ./sumocfg/freeway.sumo.cfg"): exited with code 134. Make sure you have set $PATH correctly. -- in module (Veins::TraCIScenarioManagerForker) Highway.manager (id=6), during network initialization

TRAPPING on the exception above, due to a debug-on-errors=true configuration option. Is your debugger ready?
Aborted

**Comment by michele-segata** [comment]
Please use the github issue tracker in the proper way, opening one issue for each problem you are encountering, and choose an issue message that is descriptive of your problem.

> Hi, michele-segate, thanks for your code. I install the instant plexe on my VmWare virtual machine, when I run the examples, it can run successfully by sumo. But I want to run it in sumo-gui, it stucks in the map loading interface. Before run examples, I just run:
> 
> `python "/home/plexe/src/plexe-veins/sumo-launchd.py" -vv -c "/home/plexe/src/plexe-sumo/bin/sumo-gui"`
> 
> Can you help me find what's wrong? Thank you.

Please carefully read the [documentation](http://plexe.car2x.org/tutorial/#running-the-example). The `sumo-launchd.py` script is not required.

**Comment by michele-segata** [comment]
> when I close the sumo-gui windows, the console in omnet appear this：
> 
> > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> Plugin path: ./plugins
> Loading configuration... done.
> 
> RUNTIME ERROR. A cRuntimeError exception is about to be thrown, and you
> requested (by setting debug-on-errors=true in the ini file) that errors
> abort execution and break into the debugger.
> 
> You should now probably be running the simulation under gdb or another
> debugger. The simulation kernel will now raise a SIGINT signal which will
> get you into the debugger. If you are not running under a debugger, you can
> still use the core dump for post-mortem debugging. Once in the debugger,
> view the call stack (in gdb: "bt" command) to see the context of the
> runtime error.
> 
> <!> Error launching TraCI server ("sumo-gui --remote-port 50501 --seed 0 --configuration-file ./sumocfg/freeway.sumo.cfg"): exited with code 134. Make sure you have set $PATH correctly. -- in module (Veins::TraCIScenarioManagerForker) Highway.manager (id=6), during network initialization
> 
> TRAPPING on the exception above, due to a debug-on-errors=true configuration option. Is your debugger ready?
> Aborted

This is not an issue. You have closed the SUMO GUI before the simulation terminated, so Veins lost the connection to SUMO.

**Comment by ynuwm** [comment]
Thanks for your reply. You said that sumo-launchd.py script is not required. But if I don't use this script, the example in this project is still can't run extacly, it will stuck in loading *.sumocfg in the sumo-gui interface.

**Comment by michele-segata** [comment]
You need to be more specific on the error, otherwise I can't help you. For sure `sumo-launchd.py` is not required because Plexe examples use the `TraCIScenarioManagerForker` module, not the `TraCIScenarioManagerLaunchd` ([see here](https://github.com/michele-segata/plexe-veins/blob/plexe-2.1/examples/platooning/Highway.ned#L56)).
This said, the only issue that I observe is that the SUMO GUI is very very when run in the virtual machine, but it works:
<img width="1024" alt="instant-plexe" src="https://user-images.githubusercontent.com/2064511/68218192-39459a80-ffe4-11e9-96b9-9ea8cee15fbf.png">

You can try increasing the resources assigned to the VM by Virtualbox or VMWare.
