### ISSUE TITLE
Running error on Platooning example  (Invalid speed distribution)

### ISSUE THREAD

**Issue by itismeaso** [michele-segata/plexe-veins#12]
Hello michele-segate,

I am trying to run the plexe examples, I followed all the instructions on the web page (adding the path and all the rest...).
When I am trying to run the simulation from the terminal, I am getting the following error;

"Error: Invalid speed distribution when parsing vType 'vtypeauto' (distribution mean 1000.00 is larger than upper boundary 2.00)"

I very much appreciate if you please advice, thanks very much for your time in advance.
Best Regards.

**Comment by michele-segata** [comment]
Which version of the software are you working with (Plexe, Veins, SUMO)?

**Comment by itismeaso** [comment]
Thank you very much for the resply.
 I have cloned the plexe-sumo, and downloaded the plexe-veins 2.1 from the webpage and omnetpp-5.1.1.

**Comment by itismeaso** [comment]
Thank you very much for the resply.
I have cloned the plexe-sumo, and downloaded the plexe-veins 2.1 from the web-page and omnetpp-5.1.1.
 I tried the whole with the plexe-veins cloned from github but it did not work, that's why I used the above combination of the software.

**Comment by michele-segata** [comment]
You have a version mismatch between Plexe Veins and Plexe SUMO. As you can see, the `speedFactor` parameter has been changed from version `2.1` ([see here](https://github.com/michele-segata/plexe-veins/blob/plexe-2.1/examples/platooning/sumocfg/freeway.rou.xml#L2)) to version `3.0-alpha1` ([see here](https://github.com/michele-segata/plexe-veins/blob/plexe-3.0a1/examples/platooning/sumocfg/freeway.rou.xml#L2)). This means you are using an old version of Plexe Veins and a new version of SUMO.
This said, it is much better to use Plexe version `3.0-alpha1` and standard SUMO version `1.2.1`, as Plexe `2.1` is soon becoming obsolete.

**Comment by itismeaso** [comment]
Thank you  very much for the advice, I will do so.
