### ISSUE TITLE
what does these parameters mean?

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [michele-segata/plexe-veins#13]
carFollowModel="CC" tauEngine="0.5" omegaN="0.2" xi="1" c1="0.5" lanesCount="4" ccAccel="1.5" ploegKp="0.2" ploegKd="0.7" ploegH="0.5"
These parameters differ from sumo's default parameter,could you please tell me what "tauEngine="0.5" omegaN="0.2" xi="1" c1="0.5"" mean ?

**Comment by michele-segata** [comment]
`tauEngine` is the time constant of the first-order lag simulating engine dynamics (see eqs (1) and (2) in [1]). The other parameters are for the PATH CACC controller (see eqs (7)-(12) in [1] or the original article [2]).

[1] https://ans.disi.unitn.it/~segata/bibfiles/segata2014plexe.pdf
[2] https://ieeexplore.ieee.org/document/852914
