### ISSUE TITLE
How to set Platooning leader

### ISSUE THREAD

**Issue by mateen-malik** [michele-segata/plexe-veins#18]
There is a platooning example in Plexe-Veins which i executed,

The question is as follows,

There are 8 vehicles in the platooning and the leader is the third vehicle [Node(2)] 
How can we change the leader from third vehicle to any other such as the first vehicle?

![platooning_1](https://user-images.githubusercontent.com/74792496/104471436-27359380-55bb-11eb-9c05-f13139a6175d.JPG)

Thanks in advance
Best regards,

**Comment by michele-segata** [comment]
I'm sorry but I don't get your question. The leader is always the first vehicle. Why are you saying that the leader is the third?

**Comment by mateen-malik** [comment]
Because when i run the simulation the Highway.node2 starts beaconing first as shown in the screenshot i attached. So i thought the leader is the node 2 not node 0.
Sorry if i misunderstood it

**Comment by michele-segata** [comment]
Ok I see. I'm then closing this.

**Comment by mateen-malik** [comment]
But still i didnt undertand why node 2 start beaconing. If the first vehicle is the leader (i.e. node 0) then the node 0 should start the communication right?

**Comment by michele-segata** [comment]
The beaconing order has nothing to deal with the role of the vehicles. The vehicles simply have to send 10 messages per second. The starting time is random, as it would happen in real life using a protocol without synchronization. You can imagine that the first one turning the radio on is the first one starting to send messages.

**Comment by mateen-malik** [comment]
Ooook i understand now.
Thanks alot Michele for the explanation. 
I am so greatful
