### ISSUE TITLE
Gilbert Elliot model in Plexe

### ISSUE THREAD

**Issue by gargmohit24** [michele-segata/plexe-veins#20]
how to implement Gilbert Elliot model in Plexe for burst packet losses?

**Comment by michele-segata** [comment]
You can implement your artificial loss model by editing the [BaseProtocol](https://github.com/michele-segata/plexe/blob/master/src/plexe/protocols/BaseProtocol.cc) class. [Here](https://github.com/michele-segata/plexe/blob/master/src/plexe/protocols/BaseProtocol.cc#L239) is where incoming packets are delivered to the application, so you can simulate a loss there by dropping them.

**Comment by gargmohit24** [comment]
> You can implement your artificial loss model by editing the [BaseProtocol](https://github.com/michele-segata/plexe/blob/master/src/plexe/protocols/BaseProtocol.cc) class. [Here](https://github.com/michele-segata/plexe/blob/master/src/plexe/protocols/BaseProtocol.cc#L239) is where incoming packets are delivered to the application, so you can simulate a loss there by dropping them.

Thanks.
