### ISSUE TITLE
Packet error rate in Plexe

### ISSUE THREAD

**Issue by gargmohit24** [michele-segata/plexe-veins#21]
Hi! I am struggling to implement platooning with different packet error rates. Could you please advise how may I vary packet error rates in plexe?

Thanks in advance.

**Comment by michele-segata** [comment]
If you are using the latest version, you can change the [frameErrorRate](https://github.com/michele-segata/plexe/blob/master/examples/platooning/omnetpp.ini#L65) parameter of the MAC layer. If you are using an older version, you have the [packetLossRate](https://github.com/michele-segata/plexe/blob/plexe-2.1/examples/platooning/omnetpp.ini#L166) parameter of the `UnicastProtocol` module.

**Comment by gargmohit24** [comment]
Thanks for your reply. Can I implement packet drops for the CACC application just by changing the frameErrorRate parameter or do I need to implement packet loss model in Plexe? 
Any help would be appreciated.

**Comment by michele-segata** [comment]
By changing the frameErrorRate you will get artificial losses at the MAC layer.

**Comment by gargmohit24** [comment]
It worked. Thanks.
