### ISSUE TITLE
sumo-gui: not found

### ISSUE THREAD

**Issue by admf1** [michele-segata/plexe-veins#22]
Hi there. I'm trying to run the platooning example of Plexe. I was able to run the veins example of Veins. I used the command < /sumo-launchd.py -vv -c '/home/arthurfreitas/omnet-folder/sumo-1.9.2/bin/sumo-gui' > to connect Veins and Sumo.

However, I could not run Plexe. 

I'm using:

- Ubuntu 18.04
- Sumo 1.9.2
- Omnet++ 5.6.2
- Veins 5.1
- Plexe 3.0

And this is the error message that appears.

OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Qtenv...

Loading NED files from .:  1
Loading NED files from ../../src/plexe:  34
Loading NED files from ../../../veins-5.1/examples/veins:  1
Loading NED files from ../../../veins-5.1/src/veins:  43

Loading images from '/home/arthurfreitas/omnet-folder/plexe-master/images': *: 0 
Loading images from '/home/arthurfreitas/omnet-folder/veins-5.1/images': *: 0  veins/*: 0  veins/node/*: 45  veins/sign/*: 5 
Loading images from '/home/arthurfreitas/omnet-folder/omnetpp-5.6.2/images': *: 0  abstract/*: 90  background/*: 4  block/*: 320  device/*: 195  logo/*: 1  maps/*: 9  misc/*: 70  msg/*: 55  old/*: 111  status/*: 28 

sh: 1: sumo-gui: not found
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 22 (Invalid argument) on X server ":0"
      after 1023 requests (1023 known processed) with 0 events remaining.

It is not finding the sumo-gui.

**Comment by michele-segata** [comment]
Did you add your SUMO bin folder to the `PATH` in your `.bashrc` (or `.profile` or `.zshrc` or ..., depending on your shell)?

**Comment by admf1** [comment]
Yes, I did.

export SUMO_HOME="/home/arthurfreitas/omnet-folder/sumo-1.9.2"
export PATH=$PATH:/home/arthurfreitas/omnet-folder/sumo-1.9.2/bin

I have these two lines in my .bashrc.

**Comment by michele-segata** [comment]
Ok. So if you open a terminal and you type `sumo-gui`, SUMO starts right?

If that is the case, can you run the simulation from the terminal as indicated on the website and then show me the output log?

**Comment by admf1** [comment]
<Ok. So if you open a terminal and you type sumo-gui, SUMO starts right?> Yes, it does.

Michele, I don't really know what changed, but it worked. It is running simulations using command lines from the terminal and from Omnet++. Thank you!
