### ISSUE TITLE
Bernoullian loss model in Plexe

### ISSUE THREAD

**Issue by gargmohit24** [michele-segata/plexe-veins#26]
Hi Michele,

I am wondering if the Bernoullian loss model is available in Plexe to create artificial packet losses? Any leads would be appreciated.

Thanks.
Mohit

**Comment by michele-segata** [comment]
Dear Mohit,

yes, you can add artificial packet losses (independent Bernoullian losses) changing the `frameErrorRate` parameter of Veins, setting a value between 0 (no losses) and 1 (all packets dropped). The loss is receiver-based, not transmitter based.
See [here](https://github.com/michele-segata/plexe/blob/8eaba104cfc302d34fa8f81006410ea1ce1ab00c/examples/platooning/omnetpp.ini#L64).

Best,
Michele
