### ISSUE TITLE
Changing the communication topology in the plexe

### ISSUE THREAD

**Issue by wellisonS** [michele-segata/plexe-veins#29]
Hello, I have been using plexe to research platoons in different scenarios. Something I am having difficulty doing is about changing the communication topology. For example, I could not find a way to change the way cars communicate. Is there a specific file where I can manipulate this topology? Could you please help me in this regard?
Thanks

**Comment by michele-segata** [comment]
What exactly do you want to do? Because in its basic configuration, vehicles in Plexe use 802.11p broadcast beacons to send data to the others, so there is no real topology you can change. If a vehicle is close enough and there is no interference from other vehicles, the packet will be received. Otherwise it won't.
In a small platoon of 8 cars, were all vehicles are within a few meters of each other, the topology is simply a completely connected graph.

**Comment by wellisonS** [comment]
Hi Michele,
Thanks for your reply.
The main objective is to estimate the impact of different IFTs (like predecessor-following, leader-predecessor-following or 2-predecessor-following) and plot the graphs referring to the effects of communication on a platoon. To accomplish this, I have modified the communication matrix found on Sumo and used it with the Consensus controller.

![image](https://user-images.githubusercontent.com/55456161/169882772-f72a77d4-c83a-456e-bd36-fb7534b0c614.png)


const int CC_VehicleVariables::defaultL[][MAX_N_CARS] = {
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0}};

The image is just a test to see if the changes in the matrix, in fact, influenced the behaviour of Platoon in Plexe.

In the current version of plexe, is there any way to plot graphs with the communication information between cars? If not, how do I add new variables? I have not been successful in doing this so far.

**Comment by michele-segata** [comment]
Dear Wellison,

is the last question related to the private email we have been exchanging? If so, can I close this issue?

**Comment by wellisonS** [comment]
Dear Michele Segata,

Thank you so much for your patience and willingness to help me. Thanks to that, I managed to solve this problem. So, although I still have other questions, this issue has already been resolved and can be closed. 

Thank you once again for all your help.
