### ISSUE TITLE
A problem when running the Tutorial-Example 1

### ISSUE THREAD

**Issue by 510443664** [michele-segata/plexe-veins#3]
I could run the simulation successfully，but when i tried to plot the results，an error occurred

> Rscript generic-parser.R ../results/Braking_0_1.2_0.vec map-config default bra Rdata
> Error in library(omnetpp) : there is no package called ‘omnetpp’
> Calls: source -> withVisible -> eval -> eval -> library
> Execution halted
> Makefile:41: recipe for target '../results/bra.Braking_0_1.2_0.Rdata' failed
> make: *** [../results/bra.Braking_0_1.2_0.Rdata] Error 1

It happened after i ‘make’.Does anyone know how to solve it? Thanks.

env: ubuntu16.04 omnetpp5.1.1

**Comment by heinovski** [comment]
You have to install the omnetpp R package. See [this link](https://github.com/omnetpp/omnetpp-resultfiles/wiki/Tutorial-for-the-omnetpp-r-package) for a tutorial on how to install and use it.

**Comment by michele-segata** [comment]
When using Plexe-Veins, be sure to install the omnetpp R package at [this link](http://plexe.car2x.org/download/omnetpp_0.7-1.tar.gz) and not the official one.
Also, see the [documentation](http://plexe.car2x.org/building/) on the Plexe website for the install instructions.
