### ISSUE TITLE
sh: 1: sumo-gui: not found

### ISSUE THREAD

**Issue by yzy26353520** [michele-segata/plexe-veins#30]
# Describe the wrong
I start omnet from "start menu list"
Run the example of engine 
There are many errors:

> ![图片](https://user-images.githubusercontent.com/83323222/174429976-8c19aab8-dec6-42ce-a082-036b554a7465.png)
> OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
> Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR COMMERCIAL USE
> See the license for distribution terms and warranty disclaimer
> 
> Setting up Qtenv...
> 
> Loading NED files from ../platooning:  1
> Loading NED files from ../../src/plexe:  34
> Loading NED files from ../../../veins-veins-5.2/examples/veins:  1
> Loading NED files from ../../../veins-veins-5.2/src/veins:  43
> 
> Loading images from '/home/w/src/plexe-plexe-3.0/images': *: 0 
> Loading images from '/home/w/src/veins-veins-5.2/images': *: 0  veins/*: 0  veins/node/*: 45  veins/sign/*: 5 
> Loading images from '/home/w/src/omnetpp-5.6.2/images': *: 0  abstract/*: 90  background/*: 4  block/*: 320  device/*: 195  logo/*: 1  maps/*: 9  misc/*: 70  msg/*: 55  old/*: 111  status/*: 28 
> 
> sh: 1: sumo-gui: not found
> qt.qpa.xcb: QXcbConnection: XCB error: 14 (BadIDChoice), sequence: 1342, resource id: 81789194, major code: 55 (CreateGC), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 13 (BadGC), sequence: 1343, resource id: 81789194, major code: 72 (PutImage), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 13 (BadGC), sequence: 1344, resource id: 81789194, major code: 60 (FreeGC), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 14 (BadIDChoice), sequence: 1345, resource id: 81789195, major code: 139 (Unknown), minor code: 4
> qt.qpa.xcb: QXcbConnection: XCB error: 143 (Unknown), sequence: 1347, resource id: 81789195, major code: 139 (Unknown), minor code: 27
> qt.qpa.xcb: QXcbConnection: XCB error: 143 (Unknown), sequence: 1348, resource id: 81789195, major code: 139 (Unknown), minor code: 7
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 1349, resource id: 81789196, major code: 138 (Unknown), minor code: 23
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 1350, resource id: 81789196, major code: 138 (Unknown), minor code: 23
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 1351, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 9888, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 10203, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 10380, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 10412, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 13414, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 13474, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 13719, resource id: 81789196, major code: 2 (ChangeWindowAttributes), minor code: 0
> opp_run: ../../src/xcb_in.c:746：xcb_request_check: 假设 ‘!reply’ 失败。
> 

# platform 

- Ubuntu 22.04 LTS  5.15.0-39-generic  x86_64
- /home/w/src/omnetpp-5.6.2
- /home/w/src/veins-veins-5.2
- /home/w/src/plexe-plexe-3.0
- ~/.bashrc:
<pre>....
export PATH=/home/w/src/omnetpp-5.6.2/bin:$PATH
export SUMO_HOME=/home/w/src/sumo-1_8_0
export PATH=/home/w/src/sumo-1_8_0/bin:$PATH
export PATH=/home/w/.local/lib/python3.7/site-packages:$PATH
</pre>
- /etc/environment:
<pre>/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin</pre>
- w@w-NH5x:~$ dpkg -l|grep qt5
```
ii  dde-qt5integration:amd64                   5.5.17-2                                amd64        Qt5 theme integration for Deepin application
ii  libqt5concurrent5:amd64                    5.15.3+dfsg-2                           amd64        Qt 5 concurrent module
ii  libqt5core5a:amd64                         5.15.3+dfsg-2                           amd64        Qt 5 core module
ii  libqt5dbus5:amd64                          5.15.3+dfsg-2                           amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                           5.15.3+dfsg-2                           amd64        Qt 5 GUI module
ii  libqt5network5:amd64                       5.15.3+dfsg-2                           amd64        Qt 5 network module
ii  libqt5opengl5:amd64                        5.15.3+dfsg-2                           amd64        Qt 5 OpenGL module
ii  libqt5opengl5-dev:amd64                    5.15.3+dfsg-2                           amd64        Qt 5 OpenGL library development files
ii  libqt5positioning5:amd64                   5.15.3+dfsg-3                           amd64        Qt Positioning module
ii  libqt5printsupport5:amd64                  5.15.3+dfsg-2                           amd64        Qt 5 print support module
ii  libqt5qml5:amd64                           5.15.3+dfsg-1                           amd64        Qt 5 QML module
ii  libqt5qmlmodels5:amd64                     5.15.3+dfsg-1                           amd64        Qt 5 QML Models library
ii  libqt5quick5:amd64                         5.15.3+dfsg-1                           amd64        Qt 5 Quick library
ii  libqt5quickwidgets5:amd64                  5.15.3+dfsg-1                           amd64        Qt 5 Quick Widgets library
ii  libqt5sql5:amd64                           5.15.3+dfsg-2                           amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                    5.15.3+dfsg-2                           amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                           5.15.3-1                                amd64        Qt 5 SVG module
ii  libqt5test5:amd64                          5.15.3+dfsg-2                           amd64        Qt 5 test module
ii  libqt5webchannel5:amd64                    5.15.3-1                                amd64        Web communication library for Qt
ii  libqt5webengine-data                       5.15.9+dfsg-1                           all          Web content engine library for Qt - Data
ii  libqt5webenginecore5:amd64                 5.15.9+dfsg-1                           amd64        Web content engine library for Qt - Core
ii  libqt5webenginewidgets5:amd64              5.15.9+dfsg-1                           amd64        Web content engine library for Qt - Widget
ii  libqt5widgets5:amd64                       5.15.3+dfsg-2                           amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                     5.15.3-1                                amd64        Qt 5 X11 extras
ii  libqt5xdg3:amd64                           3.7.1-0ubuntu2                          amd64        Implementation of the XDG Specifications for Qt (shared lib)
ii  libqt5xdgiconloader3:amd64                 3.7.1-0ubuntu2                          amd64        Implementation of the XDG Iconloader for Qt (shared lib)
ii  libqt5xml5:amd64                           5.15.3+dfsg-2                           amd64        Qt 5 XML module
ii  qt5-gtk-platformtheme:amd64                5.15.3+dfsg-2                           amd64        Qt 5 GTK+ 3 platform theme
ii  qt5-qmake:amd64                            5.15.3+dfsg-2                           amd64        Qt 5 qmake Makefile generator tool
ii  qt5-qmake-bin                              5.15.3+dfsg-2                           amd64        Qt 5 qmake Makefile generator tool — binary file
ii  qt5dxcb-plugin:amd64                       5.0.46+git20220314-1                    amd64        Qt platform theme integration plugin for DDE
```

# what did I do
## 1. There's no error when omnet started by terminal:
```
w@w-NH5x:~$ omnetpp 
Starting the OMNeT++ IDE...
```
`property dialog`-`c/c++ build`-`environment`-`environment variablesto set`-`PATH`:
<pre>/home/w/src/omnetpp-5.6.2/bin:/home/w/.local/lib/python3.7/site-packages:/home/w/src/sumo-1_8_0/bin:/home/w/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin</pre>

Any example can run successfully.

## 2. When I open in the menu list, the error occurs
w@w-NH5x:~/src/omnetpp-5.6.2$ `make install-menu-item `
and click the omnet icon and problems occurs:
> ![图片](https://user-images.githubusercontent.com/83323222/174430438-42049e08-3d1e-4067-874f-3defa78fe50a.png)

> ![图片](https://user-images.githubusercontent.com/83323222/174430536-155b6a59-8697-4fa8-b625-6f746adc3f1c.png)
> An internal error occurred during: "C/C++ Indexer".
> java.nio.BufferUnderflowException

Run veins_launchd
w@w-NH5x:~$ `python3 veins_launchd -vv -c /home/w/src/sumo-1_8_0/bin/sumo`

Run the example of _veins_ successfully:
![图片](https://user-images.githubusercontent.com/83323222/174430658-4f2e1cd6-0d1e-48d5-9983-878c2bab8b1a.png)

Run the example of _engine_ unsuccessfully:
![图片](https://user-images.githubusercontent.com/83323222/174430811-d25f681a-e7cd-4102-a0e7-8978b3e5a824.png)

`property dialog`-`c/c++ build`-`environment`-`environment variablesto set`-`PATH` like this, which is different from above:
<pre>/home/w/src/omnetpp-5.6.2/bin:/home/w/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin</pre>

# what effect I want
Click the omnet icon from menu-list, and then run all the examples sccessfully.
I don't want to open terminal and input `omnetpp`.

# Tks
I'm not sure if this is a problem from omnet or java, but it works well in my another computer which is Ubuntu 20.04.4 LTS. Thank you very much for your reply.

**Comment by yzy26353520** [comment]
I solved this problem by reinstalling qt.
```
sudo apt purge libqt5*
sudo apt purge qt5-*
sudo apt-get install build-essential
sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
sudo apt-get install qt5*
```
```
@w-NH5x:~$ dpkg -l|grep qt5
ii  libqt5concurrent5:amd64                    5.15.3+dfsg-2                           amd64        Qt 5 concurrent module
ii  libqt5core5a:amd64                         5.15.3+dfsg-2                           amd64        Qt 5 core module
ii  libqt5dbus5:amd64                          5.15.3+dfsg-2                           amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                           5.15.3+dfsg-2                           amd64        Qt 5 GUI module
ii  libqt5network5:amd64                       5.15.3+dfsg-2                           amd64        Qt 5 network module
ii  libqt5opengl5:amd64                        5.15.3+dfsg-2                           amd64        Qt 5 OpenGL module
ii  libqt5opengl5-dev:amd64                    5.15.3+dfsg-2                           amd64        Qt 5 OpenGL library development files
ii  libqt5printsupport5:amd64                  5.15.3+dfsg-2                           amd64        Qt 5 print support module
ii  libqt5sql5:amd64                           5.15.3+dfsg-2                           amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                    5.15.3+dfsg-2                           amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                           5.15.3-1                                amd64        Qt 5 SVG module
ii  libqt5test5:amd64                          5.15.3+dfsg-2                           amd64        Qt 5 test module
ii  libqt5widgets5:amd64                       5.15.3+dfsg-2                           amd64        Qt 5 widgets module
ii  libqt5xml5:amd64                           5.15.3+dfsg-2                           amd64        Qt 5 XML module
ii  qt5-gtk-platformtheme:amd64                5.15.3+dfsg-2                           amd64        Qt 5 GTK+ 3 platform theme
ii  qt5-qmake:amd64                            5.15.3+dfsg-2                           amd64        Qt 5 qmake Makefile generator tool
ii  qt5-qmake-bin                              5.15.3+dfsg-2                           amd64        Qt 5 qmake Makefile generator tool — binary file
```

Reinstall omnet:
```
make clean
./configure
make -j12
```

**Comment by michele-segata** [comment]
It looks strange to me that SUMO was not found and the problem was solved by simply re-installing QT... Anyway, glad that you solved it.

**Comment by yzy26353520** [comment]
I fogot a important step about sumo installing:
`david@david-PC:~/src/sumo-1_8_0/build/cmake-build$ sudo make install`
because it's not in the _readme_ file, but in [sumo.dlr.de/docs/Installing/Linux_Build.html](https://sumo.dlr.de/docs/Installing/Linux_Build.html)
Then
```
david@david-PC:~$ which sumo
/home/david/src/sumo-1_8_0/bin/sumo
```
it become like this
```
david@david-PC:~$ which sumo
/usr/local/bin/sumo
```

**Comment by michele-segata** [comment]
Installing SUMO is not necessary, because you are adding the `bin` folder to the `PATH` variable. Indeed in your example you see that `which sumo` was finding SUMO.
```bash
david@david-PC:~$ which sumo
/home/david/src/sumo-1_8_0/bin/sumo
```
The question here is why starting the simulation from the OMNeT IDE does not work. If you would have tried starting it from the command line, it would have been working for sure.
