### ISSUE TITLE
Update Example2 in Plexe guide for sucessful build

### ISSUE THREAD

**Issue by mdanish-kh** [michele-segata/plexe-veins#31]
### Issue
Following steps in example 2 lead to an unsuccessful build with compilation errors.

### Proposed Changes

![image](https://user-images.githubusercontent.com/88161975/182949542-34d151bb-4ece-4e34-88b9-7ea21fb53541.png)
Data type `SUMOReal` should be changed to `double`

![image](https://user-images.githubusercontent.com/88161975/182949949-9abd6244-b994-4e26-8e50-46b4eb43bc6a.png)
Function `TplConvert::_2double(value.c_str())` should be changed to `StringUtils::toDouble(value.c_str())`

![image](https://user-images.githubusercontent.com/88161975/182950308-bfb10001-afb7-4998-aca7-d5022b42a06f.png)
Better wording is to say replicate the changes made to `CC_Const.h` in SUMO. If the file is copy-pasted, we run into all sorts of build errors as the file in SUMO uses namespace `Plexe` while the one in plexe uses `plexe` (notice the capitalization)

![image](https://user-images.githubusercontent.com/88161975/182950753-2d11f992-81e4-4ab5-9ad3-e54bd6c8be33.png)
As a result of above modification, change namespace from `Plexe` to `plexe` here.

After these changes, I've verified the build is successful and plexe runs as expected with the new custom controller.

**Comment by michele-segata** [comment]
Thanks for pointing this out. As written in the website, this was made for an older version of Plexe and never updated. I've updated the website (changes should appear soon) following your suggestions. Thanks for the help!
