### ISSUE TITLE
Invalid Controller Selected in MSCFModel_CC

### ISSUE THREAD

**Issue by dsg1320** [michele-segata/plexe-veins#37]
I tried out the Example 2: Extending Plexe Tutorial given in the website after installing instant Plexe 3.0. 
I made the changes to source file accordingly and recompiled it. But running the simulator with command 
`plexe_run -u Cmdenv -c SinusoidalNoGui -r 6`
keeps giving error message "Invalid controller selected in MSCFModel_CC" continuously.
How can I solve this?

**Comment by michele-segata** [comment]
The error is raised [here](https://github.com/eclipse-sumo/sumo/blob/36fba19e5d0d5c51c7a589c3bb4df29a0d059f14/src/microsim/cfmodels/MSCFModel_CC.cpp#L445). Again, did you modify SUMO? After modifying SUMO, did you recompile it?

**Comment by dsg1320** [comment]
ok thank you, solved the error by recompiling SUMO. I am closing this issue.
