### ISSUE TITLE
Vehicles got collided after Implementing the MYCC controller

### ISSUE THREAD

**Issue by Sid9993** [michele-segata/plexe-veins#38]
![Screenshot (272)](https://github.com/michele-segata/plexe/assets/75777345/4eabde67-3a6f-48f8-ae10-934cc0ded8c5)
The vehicles are getting collided in the braking scenario after implementing the mycc controller following the tutorial on "extending plexe".
We used the Mycc Control Law stated in the website and the vehicles in the braking scenario are getting collided in the sumo GUI as shown above and also in Sinusoidal scenario the last 3 vehicles in an 8 vehicle platoon are not maintaining a constant inter-vehicular distance between them and rather changing now and then.
Can you suggest what should we do in order to make the situation better and also it wud be helpful if u can state on where should we make changes in the types of vehicles in order to make the platoon heterogenous?

**Comment by michele-segata** [comment]
Yes, this is to be expected. The controller is basically unstable by design, and it is just there as an example on how you can implement your own control algorithm in plexe.

**Comment by Sid9993** [comment]
> Yes, this is to be expected. The controller is basically unstable by design, and it is just there as an example on how you can implement your own control algorithm in plexe.

Ooh ok thank you.Btw any suggestions on how can I increase the efficiency of the controller and also how can I decrease the number of vehicles and all?

**Comment by michele-segata** [comment]
Well the design of a proper control algorithm requires control theory knowledge. That specific controller I implemented as an example is using a constant spacing distance but using only a predecessor-following control topology, so it is proven to be unstable.
For the number of vehicles, simply edit simulation parameters within the `omnetpp.ini` file.
