### ISSUE TITLE
Setting playground size well 

### ISSUE THREAD

**Issue by zazim13** [michele-segata/plexe-veins#39]
Hi there, 
I am trying to find a good way to set the size of my map. I keep getting the error message: 
"tried moving host to (207.850, 1211.12) which is outside the playground"
I guest it is because my cars are moving outside of the map defined by the 3 parameters *.playgroundSizeX, *.playgroundSizeY, *.playgroundSizeZ. 

I wonder if the function veins_eval_by_version does not solve this problem, but its code is nowhere to find.

Best regards
Hakim

**Comment by Sid9993** [comment]
> Hi there, I am trying to find a good way to set the size of my map. I keep getting the error message: "tried moving host to (207.850, 1211.12) which is outside the playground" I guest it is because my cars are moving outside of the map defined by the 3 parameters *.playgroundSizeX, *.playgroundSizeY, *.playgroundSizeZ.
> 
> I wonder if the function veins_eval_by_version does not solve this problem, but its code is nowhere to find.
> 
> Best regards Hakim
![image](https://github.com/michele-segata/plexe/assets/75777345/6d485bd8-2964-4acd-98e5-551bbd6d810a)

Hi Hakim,
I think u can change the params of playgroundSize here in this file.

**Comment by zazim13** [comment]
Hi, 
I am sorry my question was not precise enough. I know that I can directly set those parameters. The problem is to set them well.  I keep getting the error message because my map defined in veins is smaller than my sumo map. Then it can happen that my vehicles run outside my veins maps, throwing this error. But my analysis may be wrong.

 I wanted to know if a function exists to set the same size for the two maps to avoid this error, and I thought the veins_eval_by_version function would do that.

**Comment by michele-segata** [comment]
Dear Hakim,
this question relates to Veins, as the playground management is implemented there. So you better open an issue there.
When doing this, please be more specific. By the default, the playground size is huge (65x25 km) so a vehicle in position (207.850, 1211.12) should not be outside of the area. You mentioned

> The problem is to set them well.

When opening the issue in Veins, please specify what you mean by "well".

**Comment by zazim13** [comment]
Thanks for your answer.
