### ISSUE TITLE
Invalid speed distribution when parsing vType 'vtypeauto' 

### ISSUE THREAD

**Issue by qipengliuNTU** [michele-segata/plexe-veins#4]
I have installed all components of Plexe as Tutorial Example 1 says, but when I `./run -u Cmdenv -c Sinusoidal -r 2`, I got the following error message in SUMO GUI:
```
Loading configuration... done.
***Starting server on port 39569 ***
Loading net-file from './sumocfg/freeway.net.xml'... done (30ms).
Loading done.
Error: Invalid speed distribution when parsing vType 'vtypeauto' (distribution mean 1000.00 is larger than upper boundary 2.00)
Quitting (on error).
```
My OS is Ubuntu 16.04.  
I am running Plexe-2.1, installed through git repo. 
I have tried on another PC, but same problem occurs again.
Could you please help me with this ?  Thanks very much.

**Comment by michele-segata** [comment]
Can you please go into your plexe-sumo folder, type `git branch` in the terminal and show me the outcome? Can you also type `sumo` and show me the outcome?

**Comment by qipengliuNTU** [comment]
Thanks very much for your reply. It makes me realize that the version of SUMO I am using might be not correct. 

I have ever played with the original SUMO before I install Plexe-sumo, and the path to the original SUMO is still in the `PATH` environmental variable. 

Even though I have edited the .bashrc file by 
```
export PATH=$PATH:~/src/plexe-sumo/bin
``` 
the first SUMO executable the system finds out is still the original one, not Plexe-sumo。

Now I modify the .bashrc file by 
```
export PATH=~/src/plexe-sumo/bin:$PATH
``` 
It works as expected.

Thanks again for your help.

**Comment by michele-segata** [comment]
Yes, that is was I was suspecting. Great. Closing this.
