### ISSUE TITLE
Error in Automatically Generating the header file by OMNET++

### ISSUE THREAD

**Issue by dsg1320** [michele-segata/plexe-veins#41]
According to the Tutorial 7- Getting started with Plexe API, we tried creating an application for the Splitting scenario. But after making the changes and recompiling plexe (after recompiling sumo, omnte++ and veins) we encountered the following error:
./plexe/apps/GettingStartedApp.h:3:10: fatal error: 'plexe/messages/AbandonPlatoon_m.h' file not found
#include "plexe/messages/AbandonPlatoon_m.h"
         ^~~~~~~~~~~~~
1 error generated.
make[1]: * [Makefile:231: ../out/clang-release/src/plexe/apps/GettingStartedApp.o] Error 1
make[1]: * Waiting for unfinished jobs....
make[1]: Leaving directory '/home/plexe/src/plexe/src'
make: * [Makefile:38: all] Error 2
zsh: exit 2     make -j 2

I believe its because the given header file is to be generated automatically by the omnet++ but it hasn't. So, is recompiling the OMNET++ enough or is there any other way? Also afterwards what is the method to run this application? Is it necessary to create a seperate scenario for splitting?

**Comment by michele-segata** [comment]
Did you run `./configure` after creating `AbandonPlatoon.msg`?

**Comment by dsg1320** [comment]
Yes after creating the Abandon.msg we did recompile the whole omnet++, veins, sumo and plexe. Are we supposed to run the command right after creating AbandonPlatoon.msg in that directory before the whole recompilation?

**Comment by michele-segata** [comment]
Before recompiling, did you run `./configure` in the Plexe root directory?

**Comment by dsg1320** [comment]
yes i have

**Comment by michele-segata** [comment]
I need more output to understand. Can you do the following:
1. Run
```bash
cd /home/plexe/src/plexe/src
ls -R
```
and copy-paste the output here?
2. Run
```bash
cd /home/plexe/src/plexe/
./configure
```
and copy-paste the output here?
3. Run
```bash
cd /home/plexe/src/plexe/
make
```
and copy-paste the output here?
