### ISSUE TITLE
CACC controller Plexe v2.1 queries

### ISSUE THREAD

**Issue by mateen-malik** [michele-segata/plexe-veins#43]
Hi Michele,

I have a few questions about the CACC controller used by the platooning vehicles in the 'sinusoidal scenario' in the Plexe simulations version 2.1. These are as follows;

1a: Do the vehicles have the 'collision avoidance function' while driving in a platoon (i.e., when the CACC controller is active)? If the front vehicle gets too close to the following vehicles will the vehicle perform any safety maneuvers? 

1b: Are there any active local sensors in the platooning vehicles?

2a: Does the Plexe use the same CACC controller described on the SUMO webpage (https://sumo.dlr.de/docs/Car-Following-Models/CACC.html)?

2b: Does the CACC controller that Plexe uses, reside in Plexe or SUMO simulator?

3: Are there any specific references where I can find exactly how Plexe's CACC controller is modeled and its properties? I have been trying to find the documentation of how that controller is built and what safety properties it might have. Unfortunately, I have not been successful in finding the precise document explaining the CACC controller that Plexe uses. 

I am looking forward to hearing from you.
I really appreciate any help you can provide.

**Comment by michele-segata** [comment]
Closing due to crossposting with [this eclipse issue](https://github.com/eclipse-sumo/sumo/issues/14569).
