### ISSUE TITLE
Error Plexe v3.1 when running Example 2 - Extending Plexe

### ISSUE THREAD

**Issue by 1317569963** [michele-segata/plexe-veins#45]
In Plexe v3.1, according to Example 2
![image](https://github.com/michele-segata/plexe/assets/165975855/1b9c6f22-3c0a-40ce-b65a-2420432d2605)
After modifying the code according to Example 2, the following error will occur during the compilation process:
```
wyc@WYC:~$ cd ~/src/plexe
wyc@WYC:~/src/plexe$ ./configure --with-veins=../veins
Determining Veins version.
Found Veins version 5.2. Okay.
Configure done. You can now run 'make'.
wyc@WYC:~/src/plexe$ make
Creating script "bin/plexe_run"
make[1]: enter directory “/home/wyc/src/plexe/src”
plexe/scenarios/BaseScenario.cc
plexe/scenarios/BaseScenario.cc:68:25: error: use of undeclared identifier 'strController'
        else if (strcmp(strController, "MYCC") == 0) {
                        ^
plexe/scenarios/BaseScenario.cc:69:13: error: use of undeclared identifier 'controller'
            controller = plexe::MYCC;
            ^
2 errors generated.
make[1]: *** [Makefile:185：../out/clang-release/src/plexe/scenarios/BaseScenario.o] error 1
make[1]: leave directory“/home/wyc/src/plexe/src”
make: *** [Makefile:38：all] error 2
```
How to solve the above problem?

**Comment by michele-segata** [comment]
As written in the website, this example was built for an old version of Plexe. Now the choice of the controller is a parameter of the traffic manager, not of the scenario, so you should edit [this file instead](https://github.com/michele-segata/plexe/blob/d756bb60f2141a8928be58ab525b623534a5efff/src/plexe/mobility/TraCIBaseTrafficManager.cc#L64).
For the same reason, you must pass the controller as parameter of the traffic manager within `omnetpp.ini`.
