### ISSUE TITLE
"/usr/bin/env: 'python': No such file or directory" error when running the configure command  that is, "./configure --with-veins=../veins"

### ISSUE THREAD

**Issue by mateen-malik** [michele-segata/plexe-veins#46]
Hi, I have Ubutu 22.04 installed on my computer with Veins version 5.2 and Plexe version 3.0a2.
In order to run the plexe examples from the terminal I run the following command;

cd ~/src/plexe
./configure --with-veins=../veins

I got the following error;
/usr/bin/env: 'python': No such file or directory

My Python version is 3.10.12

Need your guidance to solve the issue.

Thanks in advance,

Best regards!

**Comment by michele-segata** [comment]
This has nothing to deal with Plexe, it is a generic Ubuntu problem. Please see [stackoverflow](https://stackoverflow.com/questions/3655306/ubuntu-usr-bin-env-python-no-such-file-or-directory/65059966#65059966) for this kind of issues.
