### ISSUE TITLE
Potential error issue in autolanechange example

### ISSUE THREAD

**Issue by ghost** [michele-segata/plexe-veins#5]
Hi, I have run the autolanechange demo and found a potential issue in the configuration of this example. As the platoon size variable “platoonSize” should be an int number to be read in RingTrafficManager.cc, **.traffic.platoonSize should be configured by using intuniform() instead of uniform() in omnetpp.ini, i.e., **.traffic.platoonSize = intuniform(3,8,5). Otherwise, a potential error would occur when casting a double to an int, such as the one stating "<!> Cannot cast 4.10097 from type double to integer (note: no implicit conversion from double to int) -- in module (RingTrafficManager) Higway.traffic (id=6), at t=0.01s, event #4" .

**Comment by michele-segata** [comment]
Hi,
yes you are right. Thanks for pointing this out. I never noticed because this casting error never occurred to me. Out of curiosity, which system and which compiler are you using?
I've fixed this in master: ad1293a8f54dc9943c11288503e10371069108c4

**Comment by ghost** [comment]
> Hi,
> yes you are right. Thanks for pointing this out. I never noticed because this casting error never occurred to me. Out of curiosity, which system and which compiler are you using?
> I've fixed this in master: [ad1293a](https://github.com/michele-segata/plexe-veins/commit/ad1293a8f54dc9943c11288503e10371069108c4)

You're welcome. My Linux system is Ubuntu 16.04 STL and I have installed OMNeT++ 5.4.1 with the GCC 5.4.0 compiler.

**Comment by michele-segata** [comment]
Ok then maybe the problem is that I am not using OMNeT++ 5.4.1, but 5.1.1.

Be careful that data extraction scripts will not work with OMNeT++ 5.4.1, as the authors modified the data logging but, I believe, not the `R` library to read them. If you want to use the data extraction scripts provided with Plexe, you need to downgrade to OMNeT++ 5.1.1 (and then recompile Plexe as well).
